format_version: 3
pipelines:
  pipeline1:
    group: first
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: asdf
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:xdrx/ilIq0/v7gFwnLJHIA==:s4GuvBFK8UL/vTzU1IqzNw==
      asfd:
        ignore_for_scheduling: true
        pipeline: up42
        stage: up42_stage
    stages:
      - stage:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            job:
              timeout: 0
              tasks:
                - exec:
                    command: ls
                    run_if: passed
                - fetch:
                    is_file: true
                    source: asfd
                    destination: ""
                    pipeline: up42
                    stage: up42_stage
                    job: up42_job
                    run_if: passed
